// <auto-generated />
using DatabaseSynchServiceUsingWorkerService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseSynchServiceUsingWorkerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240209125746_SeedingTheData")]
    partial class SeedingTheData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseSynchServiceUsingWorkerService.Models.Table1Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "9876546987",
                            Name = "SmartPhone"
                        },
                        new
                        {
                            Id = 2,
                            Contact = "9879046987",
                            Name = "Refrigerators"
                        },
                        new
                        {
                            Id = 3,
                            Contact = "9812346987",
                            Name = "TV"
                        });
                });

            modelBuilder.Entity("DatabaseSynchServiceUsingWorkerService.Models.Table2Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table2");
                });
#pragma warning restore 612, 618
        }
    }
}
